databases:
  - name: BiLaL
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: BiLaL
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 Matrix.py
    region: frankfurt
    envVars:
      - key: APP_ID
        value: "9671629"
      - key: API_HASH
        value: "be5c84e9dc1ca0e2b53d54b71e575124"
      - key: ALIVE_NAME
        sync: false
      - key: ENV
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: TZ
        value: Asia/Baghdad
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: DATABASE_URL
        fromDatabase:
          name: BiLaL
          property: connectionString
    autoDeploy: false
